// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OperationWeb.DataAccess;

#nullable disable

namespace OperationWeb.DataAccess.Migrations
{
    [DbContext(typeof(OperationWebDbContext))]
    [Migration("20251202191035_AddManagersToProyectos")]
    partial class AddManagersToProyectos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OperationWeb.DataAccess.Entities.Cuadrilla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacidadMaxima")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Activa");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Supervisor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Cuadrillas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacidadMaxima = 5,
                            Descripcion = "Equipo de trabajo zona norte",
                            Estado = "Activa",
                            FechaCreacion = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Cuadrilla Norte",
                            Supervisor = "María González",
                            Ubicacion = "Zona Norte"
                        },
                        new
                        {
                            Id = 2,
                            CapacidadMaxima = 4,
                            Descripcion = "Equipo de trabajo zona sur",
                            Estado = "Activa",
                            FechaCreacion = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Cuadrilla Sur",
                            Supervisor = "Juan Pérez",
                            Ubicacion = "Zona Sur"
                        },
                        new
                        {
                            Id = 3,
                            CapacidadMaxima = 6,
                            Descripcion = "Equipo de trabajo zona centro",
                            Estado = "Inactiva",
                            FechaCreacion = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Cuadrilla Centro",
                            Supervisor = "Carlos Rodríguez",
                            Ubicacion = "Zona Centro"
                        });
                });

            modelBuilder.Entity("OperationWeb.DataAccess.Entities.CuadrillaColaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CuadrillaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("FechaDesasignacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("PersonalDNI")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Rol")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PersonalDNI");

                    b.HasIndex("CuadrillaId", "PersonalDNI", "Activo")
                        .IsUnique()
                        .HasFilter("[Activo] = 1");

                    b.ToTable("CuadrillaColaboradores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CuadrillaId = 1,
                            FechaAsignacion = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PersonalDNI = "87654321",
                            Rol = "Supervisor"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CuadrillaId = 1,
                            FechaAsignacion = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PersonalDNI = "12345678",
                            Rol = "Técnico"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CuadrillaId = 2,
                            FechaAsignacion = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PersonalDNI = "11223344",
                            Rol = "Operario"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CuadrillaId = 2,
                            FechaAsignacion = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            PersonalDNI = "44332211",
                            Rol = "Técnico"
                        });
                });

            modelBuilder.Entity("OperationWeb.DataAccess.Entities.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleado"));

                    b.Property<bool?>("Administrador")
                        .HasColumnType("bit");

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApellidoPaterno")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodigoEmpleado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdArea")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmpleadoPerfil")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int?>("IdJefeInmediato")
                        .HasColumnType("int");

                    b.Property<int?>("IdUnidad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TipoDocumento")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioActivo")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEmpleado");

                    b.HasIndex("CodigoEmpleado")
                        .IsUnique()
                        .HasFilter("[CodigoEmpleado] IS NOT NULL");

                    b.HasIndex("DNI")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Empleado", (string)null);

                    b.HasData(
                        new
                        {
                            IdEmpleado = 1,
                            ApellidoPaterno = "Pérez",
                            DNI = "12345678",
                            Email = "juan.perez@empresa.com",
                            FechaCreacion = new DateTime(2025, 12, 2, 19, 10, 34, 730, DateTimeKind.Utc).AddTicks(920),
                            IdEmpresa = 0,
                            Nombre = "Juan",
                            Telefono = "555-0001"
                        },
                        new
                        {
                            IdEmpleado = 2,
                            ApellidoPaterno = "González",
                            DNI = "87654321",
                            Email = "maria.gonzalez@empresa.com",
                            FechaCreacion = new DateTime(2025, 12, 2, 19, 10, 34, 730, DateTimeKind.Utc).AddTicks(920),
                            IdEmpresa = 0,
                            Nombre = "María",
                            Telefono = "555-0002"
                        },
                        new
                        {
                            IdEmpleado = 3,
                            ApellidoPaterno = "Rodríguez",
                            DNI = "11223344",
                            Email = "carlos.rodriguez@empresa.com",
                            FechaCreacion = new DateTime(2025, 12, 2, 19, 10, 34, 730, DateTimeKind.Utc).AddTicks(920),
                            IdEmpresa = 0,
                            Nombre = "Carlos",
                            Telefono = "555-0003"
                        },
                        new
                        {
                            IdEmpleado = 4,
                            ApellidoPaterno = "López",
                            DNI = "44332211",
                            Email = "ana.lopez@empresa.com",
                            FechaCreacion = new DateTime(2025, 12, 2, 19, 10, 34, 730, DateTimeKind.Utc).AddTicks(920),
                            IdEmpresa = 0,
                            Nombre = "Ana",
                            Telefono = "555-0004"
                        });
                });

            modelBuilder.Entity("OperationWeb.DataAccess.Entities.HistorialCargaPersonal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualizadosSnapshot")
                        .HasColumnType("int");

                    b.Property<string>("Archivo")
                        .HasMaxLength(520)
                        .HasColumnType("nvarchar(520)");

                    b.Property<int?>("Duplicados")
                        .HasColumnType("int");

                    b.Property<int?>("EventosGenerados")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FilasProcesadas")
                        .HasColumnType("int");

                    b.Property<string>("Hoja")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("InsertadosSnapshot")
                        .HasColumnType("int");

                    b.Property<string>("Periodo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Usuario")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Historial_Cargas_Personal");
                });

            modelBuilder.Entity("OperationWeb.DataAccess.Entities.MotivoCese", b =>
                {
                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Codigo");

                    b.ToTable("MotivosCese");
                });

            modelBuilder.Entity("OperationWeb.DataAccess.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("OperationWeb.DataAccess.Entities.Personal", b =>
                {
                    b.Property<string>("DNI")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Area")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodigoCebe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodigoEmpleado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DetalleCebe")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Distrito")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Division")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailPersonal")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaCese")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Inspector")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("JefeInmediato")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LineaNegocio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MotivoCeseDesc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Permanencia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Seccion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sexo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DNI");

                    b.ToTable("Personal", (string)null);

                    b.HasData(
                        new
                        {
                            DNI = "12345678",
                            Distrito = "Lima",
                            FechaCreacion = new DateTime(2025, 12, 2, 19, 10, 34, 730, DateTimeKind.Utc).AddTicks(820),
                            FechaInicio = new DateTime(2025, 12, 2, 19, 10, 34, 730, DateTimeKind.Utc).AddTicks(820),
                            Inspector = "Juan Pérez",
                            Telefono = "555-0001",
                            Tipo = "Técnico"
                        },
                        new
                        {
                            DNI = "87654321",
                            Distrito = "Miraflores",
                            FechaCreacion = new DateTime(2025, 12, 2, 19, 10, 34, 730, DateTimeKind.Utc).AddTicks(830),
                            FechaInicio = new DateTime(2025, 12, 2, 19, 10, 34, 730, DateTimeKind.Utc).AddTicks(820),
                            Inspector = "María González",
                            Telefono = "555-0002",
                            Tipo = "Supervisor"
                        },
                        new
                        {
                            DNI = "11223344",
                            Distrito = "San Isidro",
                            FechaCreacion = new DateTime(2025, 12, 2, 19, 10, 34, 730, DateTimeKind.Utc).AddTicks(830),
                            FechaInicio = new DateTime(2025, 12, 2, 19, 10, 34, 730, DateTimeKind.Utc).AddTicks(830),
                            Inspector = "Carlos Rodríguez",
                            Telefono = "555-0003",
                            Tipo = "Operario"
                        },
                        new
                        {
                            DNI = "44332211",
                            Distrito = "Surco",
                            FechaCreacion = new DateTime(2025, 12, 2, 19, 10, 34, 730, DateTimeKind.Utc).AddTicks(830),
                            FechaInicio = new DateTime(2025, 12, 2, 19, 10, 34, 730, DateTimeKind.Utc).AddTicks(830),
                            Inspector = "Ana López",
                            Telefono = "555-0004",
                            Tipo = "Técnico"
                        });
                });

            modelBuilder.Entity("OperationWeb.DataAccess.Entities.PersonalEventoLaboral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DNI")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("FechaEvento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Periodo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoEvento")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("DNI");

                    b.ToTable("Personal_EventoLaboral");
                });

            modelBuilder.Entity("OperationWeb.DataAccess.Entities.PersonalStaging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Archivo")
                        .HasMaxLength(520)
                        .HasColumnType("nvarchar(520)");

                    b.Property<string>("Area")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodigoCebe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodigoEmpleado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DNI")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("DetalleCebe")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Division")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailPersonal")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaCarga")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCese")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hoja")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Inspector")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("JefeInmediato")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LineaNegocio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MotivoCeseDesc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MotivoDeCese")
                        .HasColumnType("int");

                    b.Property<string>("MotivoNorm")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Periodo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("Permanencia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Seccion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SedeTrabajo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sexo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Situacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoTrabajador")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioCarga")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DNI");

                    b.HasIndex("MotivoDeCese");

                    b.ToTable("Personal_Staging");
                });

            modelBuilder.Entity("OperationWeb.DataAccess.Entities.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cliente")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Division")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaSincronizacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("GerenteDni")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("JefeDni")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Presupuesto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("OperationWeb.DataAccess.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("OperationWeb.DataAccess.Entities.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("OperationWeb.DataAccess.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DNI")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OperationWeb.DataAccess.Entities.UserActivation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssuedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserActivations");
                });

            modelBuilder.Entity("OperationWeb.DataAccess.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("OperationWeb.DataAccess.Entities.CuadrillaColaborador", b =>
                {
                    b.HasOne("OperationWeb.DataAccess.Entities.Cuadrilla", "Cuadrilla")
                        .WithMany("CuadrillaColaboradores")
                        .HasForeignKey("CuadrillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OperationWeb.DataAccess.Entities.Personal", "Personal")
                        .WithMany()
                        .HasForeignKey("PersonalDNI")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuadrilla");

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("OperationWeb.DataAccess.Entities.PersonalEventoLaboral", b =>
                {
                    b.HasOne("OperationWeb.DataAccess.Entities.Personal", "Personal")
                        .WithMany()
                        .HasForeignKey("DNI");

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("OperationWeb.DataAccess.Entities.PersonalStaging", b =>
                {
                    b.HasOne("OperationWeb.DataAccess.Entities.Personal", "Personal")
                        .WithMany()
                        .HasForeignKey("DNI");

                    b.HasOne("OperationWeb.DataAccess.Entities.MotivoCese", "MotivoCeseNavigation")
                        .WithMany()
                        .HasForeignKey("MotivoDeCese");

                    b.Navigation("MotivoCeseNavigation");

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("OperationWeb.DataAccess.Entities.UserActivation", b =>
                {
                    b.HasOne("OperationWeb.DataAccess.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OperationWeb.DataAccess.Entities.UserRole", b =>
                {
                    b.HasOne("OperationWeb.DataAccess.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OperationWeb.DataAccess.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OperationWeb.DataAccess.Entities.Cuadrilla", b =>
                {
                    b.Navigation("CuadrillaColaboradores");
                });
#pragma warning restore 612, 618
        }
    }
}
