// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OperationWeb.DataAccess;

#nullable disable

namespace OperationWeb.DataAccess.Migrations
{
    [DbContext(typeof(OperationWebDbContext))]
    [Migration("20251030013228_AddEmpleadoEntity")]
    partial class AddEmpleadoEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OperationWeb.DataAccess.Entities.Colaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Documento")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Activo");

                    b.Property<DateTime>("FechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique()
                        .HasFilter("[Documento] IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Colaboradores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Pérez",
                            Cargo = "Técnico",
                            Documento = "12345678",
                            Email = "juan.perez@empresa.com",
                            Estado = "Activo",
                            FechaIngreso = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Juan",
                            Telefono = "555-0001"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "González",
                            Cargo = "Supervisor",
                            Documento = "87654321",
                            Email = "maria.gonzalez@empresa.com",
                            Estado = "Activo",
                            FechaIngreso = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "María",
                            Telefono = "555-0002"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Rodríguez",
                            Cargo = "Operario",
                            Documento = "11223344",
                            Email = "carlos.rodriguez@empresa.com",
                            Estado = "Activo",
                            FechaIngreso = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Carlos",
                            Telefono = "555-0003"
                        },
                        new
                        {
                            Id = 4,
                            Apellido = "López",
                            Cargo = "Técnico",
                            Documento = "44332211",
                            Email = "ana.lopez@empresa.com",
                            Estado = "Activo",
                            FechaIngreso = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Ana",
                            Telefono = "555-0004"
                        });
                });

            modelBuilder.Entity("OperationWeb.DataAccess.Entities.Cuadrilla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacidadMaxima")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Activa");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Supervisor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Cuadrillas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacidadMaxima = 5,
                            Descripcion = "Equipo de trabajo zona norte",
                            Estado = "Activa",
                            FechaCreacion = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Cuadrilla Norte",
                            Supervisor = "María González",
                            Ubicacion = "Zona Norte"
                        },
                        new
                        {
                            Id = 2,
                            CapacidadMaxima = 4,
                            Descripcion = "Equipo de trabajo zona sur",
                            Estado = "Activa",
                            FechaCreacion = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Cuadrilla Sur",
                            Supervisor = "Juan Pérez",
                            Ubicacion = "Zona Sur"
                        },
                        new
                        {
                            Id = 3,
                            CapacidadMaxima = 6,
                            Descripcion = "Equipo de trabajo zona centro",
                            Estado = "Inactiva",
                            FechaCreacion = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Cuadrilla Centro",
                            Supervisor = "Carlos Rodríguez",
                            Ubicacion = "Zona Centro"
                        });
                });

            modelBuilder.Entity("OperationWeb.DataAccess.Entities.CuadrillaColaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<int>("CuadrillaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("FechaDesasignacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rol")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("CuadrillaId", "ColaboradorId", "Activo")
                        .IsUnique()
                        .HasFilter("[Activo] = 1");

                    b.ToTable("CuadrillaColaboradores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            ColaboradorId = 2,
                            CuadrillaId = 1,
                            FechaAsignacion = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rol = "Supervisor"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            ColaboradorId = 1,
                            CuadrillaId = 1,
                            FechaAsignacion = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rol = "Técnico"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            ColaboradorId = 3,
                            CuadrillaId = 2,
                            FechaAsignacion = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rol = "Operario"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            ColaboradorId = 4,
                            CuadrillaId = 2,
                            FechaAsignacion = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rol = "Técnico"
                        });
                });

            modelBuilder.Entity("OperationWeb.DataAccess.Entities.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleado"));

                    b.Property<bool?>("Administrador")
                        .HasColumnType("bit");

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApellidoPaterno")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodigoEmpleado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdArea")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmpleadoPerfil")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int?>("IdJefeInmediato")
                        .HasColumnType("int");

                    b.Property<int?>("IdUnidad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TipoDocumento")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioActivo")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEmpleado");

                    b.HasIndex("CodigoEmpleado")
                        .IsUnique()
                        .HasFilter("[CodigoEmpleado] IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("NumeroDocumento")
                        .IsUnique()
                        .HasFilter("[NumeroDocumento] IS NOT NULL");

                    b.ToTable("Empleado", (string)null);
                });

            modelBuilder.Entity("OperationWeb.DataAccess.Entities.CuadrillaColaborador", b =>
                {
                    b.HasOne("OperationWeb.DataAccess.Entities.Colaborador", "Colaborador")
                        .WithMany("CuadrillaColaboradores")
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OperationWeb.DataAccess.Entities.Cuadrilla", "Cuadrilla")
                        .WithMany("CuadrillaColaboradores")
                        .HasForeignKey("CuadrillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("Cuadrilla");
                });

            modelBuilder.Entity("OperationWeb.DataAccess.Entities.Colaborador", b =>
                {
                    b.Navigation("CuadrillaColaboradores");
                });

            modelBuilder.Entity("OperationWeb.DataAccess.Entities.Cuadrilla", b =>
                {
                    b.Navigation("CuadrillaColaboradores");
                });
#pragma warning restore 612, 618
        }
    }
}
